import { Document, Page, Text, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import React from 'react';

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 11, fontFamily: 'Helvetica' },
  h1: { fontSize: 20, marginBottom: 8 },
  h2: { fontSize: 14, marginTop: 12, marginBottom: 4 },
  para: { marginBottom: 6, lineHeight: 1.4 },
});

interface ReportProps {
  ngoName: string;
  summary: string;
  keyFindings: string[];
  recommendations: string[];
}

export function DiscoveryReport(props: ReportProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Dalgo Discovery Report</Text>
        <Text style={styles.para}>Prepared for: {props.ngoName}</Text>
        <Text style={styles.h2}>Summary</Text>
        <Text style={styles.para}>{props.summary}</Text>
        <Text style={styles.h2}>Key findings</Text>
        {props.keyFindings.map((f, i) => (
          <Text key={i} style={styles.para}>
            • {f}
          </Text>
        ))}
        <Text style={styles.h2}>Recommendations</Text>
        {props.recommendations.map((r, i) => (
          <Text key={i} style={styles.para}>
            {i + 1}. {r}
          </Text>
        ))}
        <Text style={[styles.para, { marginTop: 16, fontSize: 9, color: '#666' }]}>
          Generated by the Dalgo Discovery Bot.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderReportPdf(props: ReportProps): Promise<Buffer> {
  return await renderToBuffer(<DiscoveryReport {...props} />);
}
